### PR TITLE
Add world latency

### PR DESCRIPTION
**Pull request by pierd**

### CODE REVIEW

**Comment by chaosprint** [comment]
LGTM. btw do you think that we can add a ping latency display in the UI?

**Review by philpax — APPROVED** [review]
Also LGTM, but would also suggest using a UI with `use_query` so that you have active feedback. Another fun idea would be to integrate it into the scoreboard.

**Comment by chaosprint** [comment]
> Also LGTM, but would also suggest using a UI with `use_query` so that you have active feedback. Another fun idea would be to integrate it into the scoreboard.

I was thinking the same on merging that to scoreboard @pierd

**Comment by pierd** [comment]
Sure. I'm going to keep the console too because I want to have it visible even if UI has some serious issues.

Where do the character codes for icons used in scoreboard come from?

**Comment by chaosprint** [comment]
> Sure. I'm going to keep the console too because I want to have it visible even if UI has some serious issues.
> 
> Where do the character codes for icons used in scoreboard come from?

https://www.nerdfonts.com/cheat-sheet

**Comment by pierd** [comment]
> > Sure. I'm going to keep the console too because I want to have it visible even if UI has some serious issues.
> > Where do the character codes for icons used in scoreboard come from?
> 
> https://www.nerdfonts.com/cheat-sheet

Nice. I picked ⌛ for it (`nf-fa-hourglass_start`)

**Pull request merged**
